version: '1.0'

services:
  # mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # node API service
  api:
    env_file:
      - .env.prod
    build: .
    ports:
      # local-container
      - 80:80
      - 443:443
    environment:
      PORT: 443
      DB_NAME: podcasts
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}